import type { Metadata } from "next";
import { Fira_Code, Fira_Sans } from "next/font/google";
import "./globals.css";
import Grid from "../components/grid";
import Header from "../components/ui/header";
import Navbar from "../components/ui/navbar";

const fira_code = Fira_Code({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fira-code",
});

const fira_sans = Fira_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fira-sans",
  weight: ["200", "400", "600", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={fira_code.className + " main-grid py-8"}>
        <Header className="fixed top-0 left-0 right-0 p-4 md:p-8 h-40 z-50" /> 
        {/* grid-def */}
        <Navbar className="z-50" />
        {/* grid-def */}
        <main className="col-span-full">{children}</main>
        <footer className="mb-32">Designed &amp; Built in the PNW</footer>
        <Grid className="h-svh w-svw" />
      </body>
    </html>
  );
}
